### ISSUE TITLE
적 처치 시 일정 확률로 강화아이템 드랍

### ISSUE THREAD

**Issue by Kim-Yongjun** [inureyes/Galtron#102]
- 적을 처치 했을 때(1스테이지에 한번) 일정 확률로 무기 강화(총알이 한명을 맞춘 후 소멸이 아니라 관통한다.) 아이템 드랍

**Comment by Ramenseller** [comment]
I'll take it

**Comment by SonMinWoo** [comment]
I'll take it

**Comment by Keunmo** [comment]
i'll take it (with SonMinWoo)
