### ISSUE TITLE
점수산출 방식 변경

### ISSUE THREAD

**Issue by TideProphet** [inureyes/Galtron#106]
현재 Galtron의 점수 산출공식은 스테이지가 올라갈수록 점수 증가량이 너무 큽니다. 
그렇기 때문에 약 40~50스테이지를 넘어갈 경우 스코어보드의 사이즈를 넘어서는 점수가 발생합니다. 
따라서 점수 산출방식을 좀 더 세밀화하고, 기본 산출공식을 수정해야 합니다.

**Comment by PrismSpirit** [comment]
I'll take it.

**Comment by inureyes** [comment]
@PrismSpirit if you delete `self.scoreSpeedUp = 1.1`, every scoring routine related to that variable will stop working. Need a better solution.

**Comment by Taewan-P** [comment]
@PrismSpirit ![image](https://user-images.githubusercontent.com/27392567/38260472-a4a6bb62-37a2-11e8-9bf0-2414c10911ca.png)
점수 인플레이션이 다시 생겼습니다...

**Comment by Taewan-P** [comment]
특히 5스테이지 부터 갑자기 증가합니다. 참고바랍니다

**Comment by Taewan-P** [comment]
이슈를 새로 파겠습니당...
