### ISSUE TITLE
적의 공격개시 판단 개선

### ISSUE THREAD

**Issue by TideProphet** [inureyes/Galtron#107]
적들의 공격개시 방식은 플레이어의 기체가 적기의 바로 아래를 지나칠 때만 사격을 개시하는 방식입니다. 
* **적기가 무작위성이 포함된 유동적인 탄막을 형성하도록 변경하여** 

게임의 단조로운 난이도를 해결해야 합니다.

**Comment by RDCPP** [comment]
회성이는 비추야

**Comment by hy-kiera** [comment]
i will take it

**Comment by hy-kiera** [comment]
I solved this issue and upstream merged it.
So, you need to close this issue.
