### ISSUE TITLE
시작 전 잔기(목숨) 변경기능

### ISSUE THREAD

**Issue by YeomJihoon** [inureyes/Galtron#120]
시작을 누른 후 ◀  n  ▶  의 간단한 화면이 나오게 합니다.
이 때 n은 기본 잔기 개수입니다.
"<" 를 누르면 잔기 개수가 감소(최소치는 한 번 죽으면 끝이고 이것을 0으로 둡니다)
">" 를 누르면 잔기 개수가 증가(최대치는 5 정도가 적합해보입니다)합니다.
설정 후 START 버튼을 누르면 조정한 개수를 반영해서 게임 시작이 이루어집니다.
※ 이 설정 화면을 연장시키면 다른 분들이 제시한 난이도 조절, 기체 종류 조절 등을 한 화면에서 할 수 있을 것 같습니다.

**Comment by Choyongil** [comment]
I'll take it
