### ISSUE TITLE
다양한 효과음 추가

### ISSUE THREAD

**Issue by SonMinWoo** [inureyes/Galtron#123]
1. 적 및 아군 기체가 공격할 시 나는 효과음 추가
2. 적 및 아군 기체가 사망하였을 시 나는 효과음 추가
3. 게임 시작 및 게임 종료시 나는 효과음 추가
4. 기타 추가가 필요하다고 생각되는 효과음 추가

**Comment by gunoong011** [comment]
i will take it

**Comment by moonkihun** [comment]
i will take it

**Comment by hyobins** [comment]
i'll take it
