### ISSUE TITLE
화면 상에서 캐릭터 순환이 가능한 모드 만들기

### ISSUE THREAD

**Issue by Ochodus** [inureyes/Galtron#125]
캐릭터가 화면의 왼쪽 끝으로 갈시 오른쪽 끝으로 이동, 오른쪽 끝으로 갈 시 왼쪽 끝으로 이동할 수 있는 모드 만들기 (또는 그렇게 설정할 수 있게 하기)

**Comment by hy-kiera** [comment]
I'll take it

**Comment by hy-kiera** [comment]
I solved it and requested to merge so you can close this issue

**Comment by hy-kiera** [comment]
Please close this issue
