### ISSUE TITLE
도탄 지원

### ISSUE THREAD

**Issue by Aricsa** [inureyes/Galtron#126]
적과 자신의 탄막이 겹치면 소멸

**Comment by Taewan-P** [comment]
I will take it

**Comment by inureyes** [comment]
I think it should be an option.

**Comment by Taewan-P** [comment]
okay :)

**Comment by hy-kiera** [comment]
I'll take it

**Comment by hy-kiera** [comment]
@inureyes 기체 색깔 선택하는 playMenu에서 요격이 가능하게 할 것인지 아닌지 선택할 수 있게 구현하는 건가요??
