### ISSUE TITLE
목숨 아이템

### ISSUE THREAD

**Issue by Choihaeun** [inureyes/Galtron#127]
1. 기본적으로 목숨 1개로 시작
2. 게임 진행시 적이 없어지며 목숨 아이템 드랍
3. 아이템 먹으면 목숨 1 UP

**Comment by Taewan-P** [comment]
I'll take it.

**Comment by inureyes** [comment]
`Maybe` score-related life item?

**Comment by RDCPP** [comment]
i will take it

**Comment by Keunmo** [comment]
issue 102랑 겹치는거 같습니다만..?

**Comment by inureyes** [comment]
@Keunmo 딱히 겹치진 않는것 같네요. 중복 구현을 막기 위해 아이템 처리에 대한 통합 프레임웍이 필요하겠네요.

**Comment by Taewan-P** [comment]
현재 적을 죽이면 일정 확률로 목숨 아이템이 드랍됩니다. 따라서 이슈를 닫겠습니다...
