### ISSUE TITLE
아이템 사용으로 적의 속도 느리게하기

### ISSUE THREAD

**Issue by TigerP-MS** [inureyes/Galtron#131]
아이템을 사용하면 일정시간동안 적의 총알의 속도와 적의 이동속도가 느려진다.

**Comment by Ochodus** [comment]
I'll take it.

**Comment by inureyes** [comment]
@Ochodus current code supports slow option by pressing `q` key. You can find the code and reuse them to support this feature. 👍

**Comment by wkd2314** [comment]
I'll take it since 12days has passed!
