### ISSUE TITLE
Pull Request를 남길때

### ISSUE THREAD

**Issue by Taewan-P** [inureyes/Galtron#154]
지금 Pull requests들을 보면 몇몇 코드가 pyc 파일들때문에 merge가 불가능하다는 옵션이 나옵니다.
.gitignore 에 \_\_pycache\_\_ 폴더랑 .pyc 파일들을 추가하는게 어떨지 묻고 싶습니다... @inureyes

**Comment by inureyes** [comment]
추가가 되어 있는데 기존걸 지우질 못했습니다. 컴 안들고 출장와서...

**Comment by inureyes** [comment]
해결 완료.

**Comment by Taewan-P** [comment]
앗 이제 봤습니다...
