### ISSUE TITLE
남은 목숨이 보이지 않는 버그

### ISSUE THREAD

**Issue by hy-kiera** [inureyes/Galtron#158]
처음 플레이가 종료된 후 나오는 버튼들에서 play를 누르면 게임이 다시 시작되는데, 라이프가 보이지 않는다.
2개부터는 보인다.

**Comment by StillnessFate** [comment]
i will take it

**Comment by StillnessFate** [comment]
7f03c8e I fixed this problem and sent a pull request.

**Comment by StillnessFate** [comment]
8af070b Resolved.
