### ISSUE TITLE
현재 이슈 해결 및 Pull Request관련

### ISSUE THREAD

**Issue by StillnessFate** [inureyes/Galtron#162]
현재 Pull Request들을 교수님이 확인하고 merge하고 계시는데, 만약 한동안 merge가 이루어지지 않고 있는 상태에서 복수의 이슈를 해결할 때의 Pull Request를 어떻게 보내면 좋을지 알고 싶습니다.

해결한 이슈 A와 B가 있다고 할 때,

1. A 이슈를 해결한 뒤 그 내용을 Pull Request를 보내고, B 이슈는 A 이슈를 해결한 상태를 포함하여 해결한 뒤 Pull Request를 보낸다. (now + issue A, now + issue A + issue B)

2. A 이슈를 해결한 뒤 그 내용을 Pull Request를 보내고, B 이슈는 A 이슈를 해결하기 전의 현재 Pull Request를 보내고자 하는 branch의 상태로 롤백한 후 B 이슈를 해결한 내용만 포함하여 Pull Request를 보낸다. (now + issue A, now + issue B)

3. A 이슈를 해결한 뒤 B 이슈를 해결한 내용을 Pull Request 할 때 이전 A 이슈에 대한 Pull Request를 Close하고, A 이슈와 B 이슈가 모두 해결된 것을 하나의 Pull Request로 보낸다. (now + issue A + issue B)

어떤 게 가장 적절한가요?

**Comment by hy-kiera** [comment]
1번 방법(?)으로 하고 있는데, A코드는 이미 Pull Request가 되어있는 상태에서 A+B가 된 코드를 request보내면 이전에 발행했던 request에 합쳐져서 A+B의 Pull Request 한개만 생성되고 있어...

**Comment by inureyes** [comment]
보통은 이슈별로 다 별도로 브렌치를 만들고, pull-request를 하는 것이 정석입니다.
