### ISSUE TITLE
적이 총알을 쏘지 않는 에러

### ISSUE THREAD

**Issue by Keunmo** [inureyes/Galtron#163]
먼저 무리중에 가운데 있는 적들을 먼저 제거하고 플레이어가 그 공간에 위치할 경우 적들이 플레이어를 공격하지 않음. 그 상태로 시간이 경과하면 적들이 화면 아래로 사라지고 게임이 계속 끝나지 않음. 

VVV        VVV
VV          VVV
VVV          VV

         A
---------------
위 상황에서 적은 플레이어를 공격하지 못함. 시간이 지나면 적들은 플레이어 옆으로 그냥 내려가버림.

**Comment by Taewan-P** [comment]
이거 이미 있는 issue이지 싶은데

**Comment by Taewan-P** [comment]
Issue #107

**Comment by hy-kiera** [comment]
ship의 위치에 상관없이 쏘는 코드로 해결함

**Comment by Keunmo** [comment]
ㅇㅎ 감사
