### ISSUE TITLE
한 화면에 쏠 수 있는 총알 횟수 제한

### ISSUE THREAD

**Issue by inureyes** [inureyes/Galtron#166]
* 현재 총알은 엄청나게 많이 쏠 수 있기 때문에 게임 성능 및 밸런스에 문제가 됩니다.
 * 화면 안에 발사할 수 있는 총알 횟수를 제안합니다.
 * [x] 총알 횟수를 적절하게 제한합니다. 
 * [x] 총알이 날아가는 속도를 빠르게 합니다.

**Comment by Taewan-P** [comment]
I will take it

**Comment by Taewan-P** [comment]
지금 총알이 날라가는 속도의 변수가 적군이 쏘는 총알의 속도랑 같은 변수를 쓰고 있습니다. 총알이 날아가는 속도를 빠르게 한다면 적군의 총알속도도 빠르게 바꿀까요? 아니면 둘이 속도를 다르게 설정할까요?

**Comment by Taewan-P** [comment]
0f80847 와 91a4f28 로 해결완료하고 Pull Request 보냈습니다.

**Comment by Taewan-P** [comment]
코드가 많이 수정되면서 총알발사횟수 조절 코드가 사라졌습니다... 다시 수정하도록 하겠습니다

**Comment by Taewan-P** [comment]
벌써 해결이 완료된것 같군요 #228
