### ISSUE TITLE
적 총알에 맞아서 다시 태어났을때 남은 적의 수와 위치가 초기화 됩니다

### ISSUE THREAD

**Issue by Taewan-P** [inureyes/Galtron#174]
적 총알에 맞고 다시 태어났을때 남은 적의 수와 위치가 초기화 됩니다. 보통 이런 게임에서 죽으면 다음 스테이지로 넘어가지 않고 죽은 그상태에서 다시 태어납니다. 따라서 남은 적의 수와 위치가 초기화되지 않게끔 바뀌었으면 좋겠습니다.

**Comment by jil8885** [comment]
i fix it and pull request this problem

**Comment by inureyes** [comment]
@jil8885 please paste the pull request url to here.

**Comment by jil8885** [comment]
https://github.com/inureyes/Galtron/pull/170

해당 pull request에서 머지된 소스에 포함되어 있습니다.
