### ISSUE TITLE
한 스테이지를 클리어 한 후에

### ISSUE THREAD

**Issue by Taewan-P** [inureyes/Galtron#175]
적군이 총알을 발사했습니다. 하지만 플레이어가 먼저 적을 모두 죽였습니다. 그러면 다음 스테이지로 넘어갑니다. 하지만 총알은 계속 날라가고 있습니다.

다음 스테이지로 넘어갈때 총알이 다 지나갈때까지 시간간격을 두거나 새 스테이지가 시작될때 화면에 있는 총알들을 모두 없어지게끔 수정하면 좋을것 같습니다.

**Comment by jil8885** [comment]
i fix it and pull request this problem
