### ISSUE TITLE
점수를 너무 많이 획득했을때

### ISSUE THREAD

**Issue by Taewan-P** [inureyes/Galtron#176]
![image](https://user-images.githubusercontent.com/27392567/38183909-ea0ab6ec-367e-11e8-8b09-1198e2b61912.png)
현재 점수를 너무 많이 획득하면 최고기록과 현재 기록점수가 겹치는 현상이 발생합니다...
점수를 일정 자릿수 이상 획득했을 시에 글씨 크기를 조정하거나 점수를 너프하는등 해결방법이 필요합니다...

**Comment by jil8885** [comment]
i fix it and pull request this problem

**Comment by Taewan-P** [comment]
제가 해결하겠습니다...
