### ISSUE TITLE
다음 스테이지로 넘어갈 때 폭파 애니메이션이 끝난 후 멈칫함

### ISSUE THREAD

**Issue by jil8885** [inureyes/Galtron#182]
다음 스테이지로 넘어갈 때 폭파 애니메이션이 끝난후 sleep하게 해주세요. 렉이 걸린 것처럼 보입니다.

**Comment by inureyes** [comment]
@jil8885 정확히 이해가 안되니 스샷 첨부 부탁합니다.

**Comment by Taewan-P** [comment]
@inureyes https://youtu.be/fb6ittLsTFM
위 영상과 같이 다음 스테이지로 넘어갈때 폭파 애니메이션도 같이 멈추는 현상인것 같습니다.

**Comment by Taewan-P** [comment]
누가 해결하겠다고 한적은 없으나 오류가 해결되었으므로 닫겠습니다.
