### ISSUE TITLE
비행기 기울어짐 구현

### ISSUE THREAD

**Issue by inureyes** [inureyes/Galtron#183]
* [x] 비행기가 왼쪽으로 갈 때는 왼쪽으로, 오른쪽으로 갈 때는 오른쪽으로 기울어지게 만든다.
 * [x] 정지하면 다시 원래 모습으로 돌아온다.

**Comment by RDCPP** [comment]
I will take it

**Comment by Aricsa** [comment]
i will take it

**Comment by hyobins** [comment]
i will take it

**Comment by RDCPP** [comment]
I added function about this issue first

**Comment by StillnessFate** [comment]
#304
