### ISSUE TITLE
ABOUT 변경하기

### ISSUE THREAD

**Issue by ujma1234** [inureyes/Galtron#190]
기존에 있던 알수없는 ABOUT을 삭제하고
사용법, 개발자, 조작키와 같은 세부사항들을 올바르게 입력한 새로운 ABOUT을 만든다

**Comment by TigerP-MS** [comment]
i will take it

**Comment by YeomJihoon** [comment]
i finished this issue.

**Comment by Taewan-P** [comment]
Pull Request #189 로 처리완료되었습니다.
