### ISSUE TITLE
게임 버튼 안내 화면만들기

### ISSUE THREAD

**Issue by hy-kiera** [inureyes/Galtron#192]
play 버튼 누르고 나서 게임 시작하지 않고 지금까지 구현된 게임 키(조건도)와 옵션들을 소개하는 안내 스크린이 있으면 좋겠다.
방향키, 필살기 버튼, 공격방법 바꾸는 버튼 등등

**Comment by 0-taku** [comment]
i will take it

**Comment by hy-kiera** [comment]
about에 있었네요.
