### ISSUE TITLE
about UI

### ISSUE THREAD

**Issue by hy-kiera** [inureyes/Galtron#196]
<img width="550" alt="image" src="https://user-images.githubusercontent.com/27283638/38199732-c7c3995c-36cc-11e8-9f47-fde743a2e420.png">
about에 내용을 더 친절하게 바꿔주고, 버튼이 내용을 가리지 않게 하면 좋겠습니다.

**Comment by YeomJihoon** [comment]
I finished this issue.

**Comment by hy-kiera** [comment]
Pull Request 번호가 몇번이에요??

**Comment by Taewan-P** [comment]
Pull Request #189 입니당

**Comment by hy-kiera** [comment]
왜 파일이 안받아졌지;;

**Comment by inureyes** [comment]
@Taewan-P about 화면이 폭이 안맞아서 빈공간이 남는거 같습니다.

**Comment by Taewan-P** [comment]
About 쪽만 지금 빈공간이 남네요. 이건 제가 해결하겠습니다..

**Comment by inureyes** [comment]
@Taewan-P 해결해 두었습니다. 👍

**Comment by Taewan-P** [comment]
@inureyes 감사합니다!
