### ISSUE TITLE
차지샷 구현

### ISSUE THREAD

**Issue by inureyes** [inureyes/Galtron#207]
* 총알을 누르고 있다가 놓으면 차지샷이 나가게 한다.
 * 차지샷은 시간에 따라 커진다.
 * 최대 크기의 차지샷은 기본 총알의 3배로 한다. 중간 차지는 2배.
 * 차지에 걸리는 시간은 2.5초로 한다.

**Comment by StillnessFate** [comment]
I will take it

**Comment by StillnessFate** [comment]
#227 I added this feature and sent a pull request.

**Comment by StillnessFate** [comment]
#227 Completed.
