### ISSUE TITLE
Highscore.json관련 오류

### ISSUE THREAD

**Issue by anmyeondo** [inureyes/Galtron#208]
highscore.json파일이 존재하지 않을 시 오류가 발생하는 부분과 게임 종료 후 하이스코어가 저장되지 않는문제

**Comment by StillnessFate** [comment]
i will take it

**Comment by StillnessFate** [comment]
#213 I solved the problem and sent a pull request.

**Comment by StillnessFate** [comment]
#213 Resolved

**Comment by Taewan-P** [comment]
@StillnessFate 현재 디렉토리 내에서 data-files라는 폴더가 없으면 FileNotFoundError가 발생합니다. 레포에 폴더만이라도 추가하는게 어떨까요?

**Comment by inureyes** [comment]
@Taewan-P 👍
