### ISSUE TITLE
세 방향 총알 구현

### ISSUE THREAD

**Issue by inureyes** [inureyes/Galtron#209]
* 현재 tab을 누르면 총알 종류가 바뀐다.
 * 총알 패턴에 세 방향으로 나가는 총알을 추가로 구현한다.  \ | /
 * 이후에 아이템을 먹으면 총알 종류가 바뀌는 이슈와 연계할 수 있다.

**Comment by pouu97** [comment]
I'll take it

**Comment by MoonJeWoong** [comment]
I`ll take it
