### ISSUE TITLE
라이프 그래픽 변경되지 않음

### ISSUE THREAD

**Issue by hy-kiera** [inureyes/Galtron#215]
play-기체선택-pause-menu-play-이전에 선택하지 않았던 색의 ship 선택해서 플레이 하면 유저의 ship 색깔과 라이프를 나타내는 ship의 색이 동일하게 나오지 않는다. 몇번 반복해서 pause-menu-play해도 맨 처음에 선택한 ship의 색깔로 라이프가 나타난다.

**Comment by Goodkorning** [comment]
I will take it

**Comment by Goodkorning** [comment]
#246 
play버튼을 눌러야 라이프 카운트 기체가 변경되는 문제가 있습니다.
