### ISSUE TITLE
스테이지 배경을 연속된 느낌을 주는 이미지로 바꾸기

### ISSUE THREAD

**Issue by inureyes** [inureyes/Galtron#229]
* #226 에서 추가된 스테이지 배경 파일들은 기존과 다르게 연속된 스테이지의 느낌이 나지 않습니다.
 * 배경파일들 모두를 연속된 느낌을 주는 스테이지 이미지로 교체합시다.

**Comment by YeomJihoon** [comment]
* 새벽에 5스테이지마다 배경이 바뀌게 구현해 두었습니다.
이걸 하실 분은 그냥 연속된 느낌의 이미지파일만 구해서 바꾸시면 될 것 같습니다.

**Comment by inureyes** [comment]
It does not look like infinite. Pull requests are welcome!

**Comment by Taewan-P** [comment]
지금 어느정도 해결되지 않았나요? 배경확인해보니깐 연속적인 느낌이 나던데

**Comment by inureyes** [comment]
@Taewan-P 이제 background 부분이 분리가 되었습니다. #211
