### ISSUE TITLE
맥 OS에서 게임을 돌릴때

### ISSUE THREAD

**Issue by Taewan-P** [inureyes/Galtron#233]
키입력을 한글로 하고 게임을 시작하게 되는경우 일시정지 키나 궁극기 키가 작동하지 않습니다. 
게임도중에 영어로 입력을 변경하고 키를 눌러도 변화가 없기에 수정이 필요한것 같습니다.

**Comment by jil8885** [comment]
I'll fix this issue

**Comment by StillnessFate** [comment]
If this bug has been resolved please close the issue. I can not confirm this because I do not use macOS.

**Comment by Taewan-P** [comment]
@StillnessFate 넵 지금확인해볼께요

**Comment by Taewan-P** [comment]
해결완료 #280
