### ISSUE TITLE
개발자용 안내서

### ISSUE THREAD

**Issue by onnoo** [inureyes/Galtron#241]
뒤늦게 Galtron에 contribution을 하려는데 초기와 코드가 많이 달라져서 개발에 참여하기에 어려움이 많습니다.

작년 수업에서 소프트웨어에 대한 개발자용 문서를 작성했던 기억이 나서
혹시 Galtron에도 개발자용 문서를 만들 수 있을까요.

**Comment by inureyes** [comment]
네 한 번 만들어봅시다. 내일 수업때 이야기해 보도록 해요.

**Comment by StillnessFate** [comment]
#297
