### ISSUE TITLE
※Avoid conflicts and make changes after you understand the code.※

### ISSUE THREAD

**Issue by StillnessFate** [inureyes/Galtron#243]
#227 I added a charge shot via this pull request. There was no original bug, but there is currently a bug.
After analyzing the cause, we found that these pull requests are the cause. #228 #234 #235 

-#228 This problem has already been fixed in #227. The code from line 98 of the deleted gameFunctions.py here is the normal key event handling code. Also, this caused the #231 issue because of the removal of the part that sets ship.chargeGaugeStartTime in line 103.
You should not use pg.mixer.music to process sound effects on line 68 of ship.py. Sound effects should use pg.mixer.Sound. pg.mixer.music is the object that controls the background music, and the sound played by it is a single sound.
And do not upload the .DS_Store file to this project.

-#234 The changes here are not related to bugs. It rather raises a bug.

-#235 As above. The changes here are not related to bugs.

**Do not send a pull request after modifying the code without understanding it.**

**Comment by StillnessFate** [comment]
I will fix these problems after a while.

**Comment by jil8885** [comment]
I already resolve issue https://github.com/inureyes/Galtron/issues/82 by making ship.shoot variable. If you want to add charge shoot on this code, you should maintain previous functions. But you ignored this and overlapped your own code. I spent almost a week to understand its code and I almost understand about it.  You shouldn't scorn me and have to learn about modularization before you add your func.

**Comment by StillnessFate** [comment]
@jil8885 You misunderstand my modifications. I have not changed your code. (# 82 auto fire)
Your code using ship.shoot did not work because input events were duplicated due to # 192 cf2fe97 (gameFunctions.py line 87).
So I modified the duplicate code to solve this problem. And so your code worked normally.
All of the above are included in # 207.

**Comment by jil8885** [comment]
But when I pull from this repo this morning, I found that there is duplicated code on them. So I delete duplicated code. I think that at that time your code was not merged yet, so after this time, your and my code are different. I apologize you that I was out of line that I was angry at that time

**Comment by StillnessFate** [comment]
You do not need to worry about it. Probably because multiple pull requests are combined at once.
