### ISSUE TITLE
상단 UI가 제대로 표시되는 않는 문제

### ISSUE THREAD

**Issue by xodh** [inureyes/Galtron#250]
잘 표시되도록 수정합시다!

**Comment by StillnessFate** [comment]
I will take it

**Comment by Taewan-P** [comment]
@xodh 조금 더 구체적으로 설명해 주시면 좋을것 같아요

**Comment by StillnessFate** [comment]
#251 I solved the problem and sent a pull request. But i think I need to make a new HUD.

**Comment by StillnessFate** [comment]
#251 Resolved.
