### ISSUE TITLE
스테이지 올라갈때 3초간 무적 상태

### ISSUE THREAD

**Issue by hy-kiera** [inureyes/Galtron#262]
마우스로 ship을 컨트롤하면서 플레이 중에 ship이 중간에 있을 때 적을 다 처치하는 경우, 스테이지가 변하고 적이 새로 생기면 alien과 ship이 충돌해 목숨이 금방 사라진다. 스테이지가 올라가면 플레이어가 재정비를 할 수 있게 2~3초간 무적 상태(can not shoot)가 되게 한다.

**Comment by Verssae** [comment]
I will solve it
