### ISSUE TITLE
5스테이지 부터 증가하는 점수 인플레이션

### ISSUE THREAD

**Issue by Taewan-P** [inureyes/Galtron#270]
![image](https://user-images.githubusercontent.com/27392567/38260472-a4a6bb62-37a2-11e8-9bf0-2414c10911ca.png)

점수 인플레이션이 다시 생겼습니다. 특히 4스테이지 까지는 멀쩡하지만 5스테이지부터 점수가 급증합니다. 결국 20스테이지 까지 가면 점수가 사진과 같이 됩니다. 좀더 점수 증가폭을 낮췄으면 좋겠습니다. (1~4스테이지는 적당합니다.)

**Comment by PrismSpirit** [comment]
I'll take it.

**Comment by StillnessFate** [comment]
274
