### ISSUE TITLE
함선이 마우스 위치로 이동하는 문제

### ISSUE THREAD

**Issue by Verssae** [inureyes/Galtron#282]
현재 게임 내에서 함선이 마우스의 위치로 이동하는 현상이 있다. 이는 #97 이슈를 잘못 이해하고 해결하면서 생긴 버그이다. 마우스 포인터가 UI 클릭 시에 사용되도록 수정하자.

**Comment by StillnessFate** [comment]
I will solve this issue.

**Comment by StillnessFate** [comment]
#294 I solved the problem and sent a pull request.

**Comment by StillnessFate** [comment]
#294 Resolved.
