### ISSUE TITLE
궁극기를 사용할때

### ISSUE THREAD

**Issue by Taewan-P** [inureyes/Galtron#288]
궁극기를 사용할때 현재 문제점이 두가지가 있습니다.

- [ ] 궁극기가 사용되는 동안에는 총알을 쏘지 못합니다.
- [ ] 궁극기를 사용하여 한 스테이지가 끝났을때에 궁극기 총알이 남아있어서 그 다음 스테이지까지 깨버리는 경우가 발생합니다.

이 두가지를 해결하면 좋겠습니다.

**Comment by Verssae** [comment]
나중에 물 흐르듯 연속적인 스테이지 구조로 바꿀 예정이라 적을 모두 처치 할 때 플레이어가 발사한 총알이 사라지지 않도록 했습니다. (이것이 더 자연스럽지 않을까요?)
