### ISSUE TITLE
적군의 투사체 발사빈도 증가 및 아군기체 이동속도 증가

### ISSUE THREAD

**Issue by TideProphet** [inureyes/Galtron#291]
현재 게임진행시 적군 기체가 투사체를 발사하는 횟수가 너무 적습니다. 
이 때문에 게임의 난이도가 너무 낮고 회피를 위해 조작할 필요성이 적어 지루합니다.
따라서 적군이 투사체를 더 많이, 더 자주 발사하도록 수정하되 이에 플레이어가 능동적으로 대처할 수 있도록 아군기체의  이동속도를 대폭 상향시키는게 좋을거 같습니다.

* 동시에 투사체를 발사하는 적군의 수 증가
* 적군이 투사체를 다시 발사하는데 걸리는 간격 대폭 감소
* 아군 기체의 기본 이동속도를 60% 정도 증가

**Comment by Keunmo** [comment]
i'll take it

**Comment by jil8885** [comment]
I'll take it
