### ISSUE TITLE
메뉴 이동과 관련된 두 가지 버그

### ISSUE THREAD

**Issue by Alpacadabra** [inureyes/Galtron#293]
### Play 메뉴를 한번 거치고 나면 다시는 타이틀 배경음악인 galtron.mp3가 재생되지 않음

Play 메뉴로 이동한 후 타이틀로 돌아가기 위해서는
- 그대로 다시 타이틀로 돌아간다.
- 기체를 선택하면 나오는 선택지를 통해 바로 타이틀로 돌아가거나, pause 후 타이틀로 돌아간다.

위 두 가지 행동 중 하나를 취해야 하는데, 두 경우 모두 타이틀 배경음악인 galtron.mp3가 아닌 스테이지 배경음악 galtron-stage.mp3가 재생됩니다. 이후로는 어떤 짓을 해도 galtron.mp3가 재생되는 일이 없습니다.

### 게임 중 타이틀로 이동한 후 다시 게임을 시작해도 이전 게임의 일부 정보가 유지됨

게임을 플레이하다가 pause 후 타이틀로 돌아가서 다시 게임을 시작해도 완전히 초기화가 되지 않습니다. 적과 나의 포지션, 탄막, 스테이지 진행 상황 등이 유지되는 것으로 보입니다.

위 두 버그를 해결할 필요가 있습니다.
+참고로 테스트환경은 Windows 10입니다.

**Comment by Taewan-P** [comment]
@Alpacadabra 두번째 버그 사항은 #172 번 이슈와 겹칩니다. 하지만 아직 해결되지 않았기 때문에 위에 @Aricsa 님은 둘다 해결하셔도 될 것 같네요!

**Comment by Alpacadabra** [comment]
@Taewan-P 겹치는걸 뒤늦게 확인했네요. 죄송합니다.

두번째는 #172 의 예시 정도로만 생각해 주시면 감사하겠습니다.

**Comment by dudu0166** [comment]
I'll take it

**Comment by Alpacadabra** [comment]
galtron-stage 사운드가 삭제됨에 따라 더이상 진행할 필요가 없어졌습니다.

**Comment by inureyes** [comment]
@Alpacadabra 스테이지 사운드가 안나오는게 버그 아니었나요?

**Comment by Alpacadabra** [comment]
@inureyes 타이틀로 돌아가도 스테이지 bgm이 계속해서 진행되는 것이 버그였습니다.
다만 #283 에서 StillnessFate 님이 스테이지 bgm을 게임에서 제외한 것으로 알고있고 그래서 issue를 close하게 되었습니다.
