### ISSUE TITLE
Blink alien when it is damaged.

### ISSUE THREAD

**Issue by inureyes** [inureyes/Galtron#310]
* #99 의 영향으로 적들도 한 방에 안 죽습니다.
 * 도탄되었을 떄 적들이 총알을 맞았는지 알려주는 효과가 있어야 하겠습니다.
 * 일반적인 슈팅게임에서는 총에 맞으면 흰 색으로 빛이 납니다. 비슷한 효과를 넣어 봅시다.

**Comment by onnoo** [comment]
I take it.
