### ISSUE TITLE
게임 플레이중 갑자기 나오는 차지샷

### ISSUE THREAD

**Issue by Taewan-P** [inureyes/Galtron#311]
말로 상세히 설명하기 힘들어 영상을 올려봅니다.
https://www.youtube.com/watch?v=ceg72as3Emk&feature=youtu.be

영상을 편집하진 못했지만 4분부터 보시면 차지샷을 쏘지도 않았는데 차지샷이 나가는 현상이 발생합니다. 심지어 이 총알은 적군을 타격하지 못합니다. (2분 14초에도 한번 있음)

**Comment by StillnessFate** [comment]
현재도 발생하는 버그인가요?
