### ISSUE TITLE
적 기체의 폭발애니메이션 오류 해결

### ISSUE THREAD

**Issue by TideProphet** [inureyes/Galtron#313]
현재 적기체가 죽는 순간 뿐만 아니라 피격될 때 마다 폭발애니메이션이 나옵니다.
적 기체가 생명력을 모두 소모하고 파괴되었을 때만 애니메이션이 나오도록 수정해주세요

* 적기체가 죽을 때만 폭발 애니메이션이 나오도록 수정

**Comment by Verssae** [comment]
#314

**Comment by Goodkorning** [comment]
기체가 피격 되면 점점 망가져가는 것을 그래픽을 표현해주면 좋을것 같습니다.

**Comment by TideProphet** [comment]
단순한 애니메이션이 아닌 사망판정 버그로 확인되었기 때문에 #314 에 추가사항을 달고 이 이슈를 닫겠습니다.
