### ISSUE TITLE
생명력 아이템에 관한 버그

### ISSUE THREAD

**Issue by Taewan-P** [inureyes/Galtron#314]
현재 생명력 아이템이 추가되면서 여러가지 버그가 추가로 등장하였습니다.
![image](https://user-images.githubusercontent.com/27392567/38469731-6ed4ff58-3b94-11e8-86ba-b1816c608f9b.png)
 - [ ] 생명력 아이템 드랍률이 너무 높습니다. 이를 낮추어야 합니다.
 - [ ] 생명력 아이템 획득 갯수를 제한해야 합니다. 안그러면 UI를 위의 사진과 같이 가리게 됩니다.
 - [ ] 지금 적기체를 여러번 맞추어야 파괴되는데, 생명력 아이템은 기체가 파괴되지 않고 맞추기만 해도 떨어지는 경우가 있습니다. 따라서 기체가 터질 때에만 아이템이 떨어지게끔 수정해야 합니다.

**Comment by Taewan-P** [comment]
처음에 생명력 갯수를 3개로 조정하고 얻을수 있는 생명력 수는 5 정도가 적당할 것 같습니다.

**Comment by TideProphet** [comment]
@Taewan-P 생명력 개수 관련해서는 다른 변경사항과 함께 하나의 이슈로 발행해보겠습니다

**Comment by TideProphet** [comment]
생명력 아이템의 드랍률은 2~3%가 적절할 것 같습니다.

**Comment by TideProphet** [comment]
적 기체의 체력이 1보다 높은 상태에서 적 기체가 피격될 경우, 아이템을 드랍할 뿐 만아니라, 폭발애니메이션이 나오고 점수도 오릅니다. 아마도 체력이 깍일 때 마다 파괴판정이 계속 나오는 것 같습니다. 
사망관련 이슈 내용을 제가 발행한 #316 로 옮기고, 해당이슈에 존재하는 내용들을 이 이슈로 옮겨서 정리하는게 어떨까요?

**Comment by Taewan-P** [comment]
@TideProphet Verssae님이 부분적으로 해결하였습니다.
