### ISSUE TITLE
플레이어의 공격력 계수 속성 추가

### ISSUE THREAD

**Issue by TideProphet** [inureyes/Galtron#315]
추후 다른 패치를 위한 기반으로 플레이어의 공격력 계수 속성을 코드에 추가하였으면 합니다.
또한 동시에 기본 공격이외의 현재 공격에도 이 속성을 이용한 수치를 적용하여야 합니다.

& 추후 다른 아군기체를 추가할 수도 있으므로 ship객체가 가진 속성으로 만드는 것을 권장합니다.

### 플레이어의 공격력 속성을 추가

* 기본공격은 공격력 X1의 피해를 줌
* 차지샷은 1단계(풀차지 이전 발사가능 단계, 주황색)에서 X2의 피해를 풀차지 상태에서 X3의 피해를 줌
* 궁극기의 경우 X3의 피해를 줌

위와 같은 내용을 구현해주셨으면 합니다.

**Comment by wkd2314** [comment]
i will take it
