### ISSUE TITLE
적 기체의 피격 그래픽과 파괴 그래픽 분리

### ISSUE THREAD

**Issue by Goodkorning** [inureyes/Galtron#320]
적기체가 피격 되었을 때의 그래픽과

파괴 시의 그래픽 분리가 필요합니다.

**Comment by Goodkorning** [comment]
피격 되었을 때의 이펙트를 삭제하고 

점점 망가져가는 기체 그래픽을 추가하는게 더 좋을 것 같습니다.

**Comment by inureyes** [comment]
@Goodkorning 열자마자 닫은 이유가 따로 있나요? #310 번 이슈와 같은것을 해결하는 것이긴 한데요.

**Comment by Goodkorning** [comment]
#313과 같은 주제의 이슈로 생각해서 굳이 다른 이슈를 열기 보다는 밑에 코멘트로 의견 내는 것으로 선택했습니다.

**Comment by inureyes** [comment]
@Goodkorning +1
