### ISSUE TITLE
차지샷이 적을 관통하지 못하는 오류

### ISSUE THREAD

**Issue by PrismSpirit** [inureyes/Galtron#323]
적 체력 추가 이후 차지샷이 적을 관통하지 못하는 오류가 생겼습니다.

**Comment by Verssae** [comment]
@PrismSpirit 차지샷 데미지가 적 체력보다 낮은거지 오류가 아닙니다. 나중에 레벨 디자인 하면서 수정하면 될 것 같습니다.

**Comment by jil8885** [comment]
차지샷이 기존 코드가 기존 총알보다 데미지를 높인 것이 아닌, 기존 총알과 데미지는 같지만 관통이 되게 만들어졌고 이미 merge된 것으로 압니다. 총알 데미지가 적 체력보다 낮아 관통이 안 된다는 것은 말이 안됩니다.

**Comment by PrismSpirit** [comment]
@Verssae 차지샷 데미지를 100으로 설정하고 게임을 실행시켜도 1라운드에서조차 관통이 안됩니다. 오류 맞습니다.

**Comment by TideProphet** [comment]
이 문제는 기존의 코드들이 적이 총알에 닿자마자 죽을 때를 전제로하고 짜여졌기 때문에 발생한 문제로 보입니다.
레벨 디자인을 개선한다 해도 모든 적이 차지샷 한방에 죽게 설정하는 것은 해결책 이 될 수 없는게  보스라든지 다른 적을 생각하면  계속 발생할 수 밖에 없는 문제가 아닐까요? 
좀 더 근본적이 개선이 필요합니다. 하지만 해당 오류 개선이 어려우니 좀 더 설명이 자세하고 큰 이슈로 만드는 편이 좋겠네요.
