### ISSUE TITLE
생명력 아이템이 사라지는 현상 해결

### ISSUE THREAD

**Issue by TideProphet** [inureyes/Galtron#328]
현재 생명력 아이템을 획득할 시 기존에 드랍되어 있던 나머지 생명력 아이템이 전부 사라집니다.
드랍률이 조정되더라도 2개 이상의 생명력 아이템이 동시에 존재할 가능성이 없는 건 아니기 때문에 해결해야 합니다.

* 생명력 아이템 하나를 획득하면 나머지가 사라지는 현상을 해결

**Comment by jil8885** [comment]
I'll take it
