### ISSUE TITLE
차지샷의 크기가 정상적으로 적용되지 않는 문제 해결 

### ISSUE THREAD

**Issue by TideProphet** [inureyes/Galtron#329]
현재 차지샷은 충전 단계에 비래하여 크기가 커집니다. 좋은 기능이죠 :)

그런데 1단계 크기 사이즈와 2단계 크기사이즈가 뒤바뀌어 
1단계 충전 사이즈가 2단계 사이즈 탄환의 크기보다 큽니다.

* 탄환 단계 사이즈 변환을 정상적으로 적용되도록 수정

**Comment by ujma1234** [comment]
i'll take it
