### ISSUE TITLE
적의 체력증가량 조절

### ISSUE THREAD

**Issue by TideProphet** [inureyes/Galtron#331]
현재 적의 체력 증가 시스템은
~~~ 
스테이지 X 3 
~~~
과 같이 적용됩니다.
스테이지가 증가함에 따라 난이도가 올라가도록 변경한 것은 좋은 의도입니다.
하지만 단순한 상수계수가 적용되어 난이도가 너무 급격하게 올라갑니다.
이에 따라 좀더 복합적인 체력 증가량을 적용함으로써 레벨디자인을 개선하였으면 합니다.

* 체력증가량 공식을 좀 더 세밀화되게 수정
ex)
~~~
      스테이지 1 에서는 1로 시작함,
      이후 두 단계 마다 체력이 1씩 증가함 ( 2~3단계: hp=2  -> 3~4단계: hp=3)
~~~
위의 예시는 가장 간단한 해결책이며 좀 더 복잡하지만 좋은 공식을 발견하셨다면 그것을 적용하시면 됩니다.

**Comment by jil8885** [comment]
I'll take it
