### ISSUE TITLE
무적 및 게임 메커니즘 수정

### ISSUE THREAD

**Issue by Verssae** [inureyes/Galtron#333]
* 무적시 Dodged!대신 SHIELD를 기체 앞에 보이게끔 updatedInvinciblity함수를 구현
* 많은 merge로 인해 충돌 시 무적 효과를 주는 코드가 사라져있으므로 복구
* 적이 등장하는 것이 물 흐르듯 등장하는 구조로 바뀔 예정이므로, 적을 모두 죽이면 적의 총알을 모두 없애지 않고 그대로 유지시키되, 무적효과를 줌(지금은 바로 적이 생성되므로 )
* 피격 시 center로 돌아가지 않고 무적효과를 주고 모든 적 총알을 없애는 게 아닌 맞은 총알만 없앰 

* 추후에 SHIELD 대신 blink효과나 보호막 이미지 등으로 교체하면 됨

**Comment by Taewan-P** [comment]
@Verssae 이거 그래서 Merge됬나요? 만약 여기 이슈내용 Merge 됬으면 닫아주세요
