### ISSUE TITLE
SHIELD가 활성화될 때

### ISSUE THREAD

**Issue by hy-kiera** [inureyes/Galtron#336]
목숨을 잃을 때 SHIELD가 활성화되는데, 이 때 eBullet에 부딪히면 eBullet이 사라집니다.
목숨이 1개 남았을 때는 SHIELD가 활성화되어 있어도 바로 GAMEOVER됩니다.

**Comment by Taewan-P** [comment]
I will take it

**Comment by Taewan-P** [comment]
@hy-kiera 근데 정확하게 무슨 뜻인지 이해를 못했어요....

**Comment by hy-kiera** [comment]
@Taewan-P 게임을 실행시키고 목숨을 잃으면 SHIELD(무적상태)가 활성화 되는데, 그 때 alien이 쏘는 eBullet에 닿으면 닿은 eBullet이 사라집니다.(no damage이고 eBullet이 사라지게 할 지, no damage이고 eBullet에 닿아도 그냥 통과) 그리고 이와 별개로 목숨이 하나 남았을 때(screen에 비행기(목숨)가 1개 남았을 때) SHIELD가 활성화되어 있어도 그냥 GAMEOVER됩니다.(원래는 목숨이 하나 남았을 때 죽어도 목숨표시가 없고 계속 플레이 할 수 있다.)

**Comment by Taewan-P** [comment]
@hy-kiera 제가 방금 해보니깐 안그렇던데요?...

**Comment by Taewan-P** [comment]
해결완료
