### ISSUE TITLE
Pause 버튼을 누를때 나오는 화면 오류

### ISSUE THREAD

**Issue by Taewan-P** [inureyes/Galtron#337]
현재 생명력이 0인 상태에서 Pause 버튼을 누르면 게임오버 화면이 뜹니다. 물론 진짜 게임오버가 되진 않고 다시 플레이를 누르면 마저 플레이가 가능합니다. 이를 수정하면 좋을것 같습니다.

**Comment by jil8885** [comment]
![2018-04-09 11 08 47](https://user-images.githubusercontent.com/10583171/38502683-fffdfa64-3c4a-11e8-9e05-266417e7dda2.png)
저는 pause를 눌르면 오버 화면이 안나오는데 어떻게 눌러야 게임 오버 화면이 나오는지 알 수 있을까요?

**Comment by Taewan-P** [comment]
"생명력이 0 남은 상태에서 누르면"으로 수정하였습니다

**Comment by StillnessFate** [comment]
#423
