### ISSUE TITLE
잔기 아이콘 통일

### ISSUE THREAD

**Issue by inureyes** [inureyes/Galtron#342]
* 아군 비행기는 디자인이 바뀌었는데 화면 왼쪽 상단 잔기 아이콘은 동일합니다.
 * 같은 아이콘으로 맞춥시다

**Comment by hy-kiera** [comment]
하트로 바꾸는 것은 어떤가요??

**Comment by inureyes** [comment]
@hy-kiera 그것도 방법인데 슈팅게임에서 목숨이 비행기로 나오는게 일종의 클리셰입니다.
