### ISSUE TITLE
쉴드 이펙트 추가

### ISSUE THREAD

**Issue by Goodkorning** [inureyes/Galtron#345]
쉴드가 활성 되었을때 기체가 깜빡 거리거나 결계 같은 그래픽이 필요합니다.

**Comment by hwangyerim** [comment]
그래픽을 만들고 여기에 이미지 파일을 올리면 되나요? 아니면 이미지를 python에 코드화해서 실제로 작동되게까지 만들어야 하나요?

**Comment by inureyes** [comment]
@hwangyerim 그래픽은 위에 올라왔으니 코드를 만들 차례가 된 듯 합니다.

**Comment by inureyes** [comment]
@hwangyerim 더 나은 그래픽이 있다면 여기에 올려도 됩니다!

**Comment by MoonJeWoong** [comment]
i'll take it
