### ISSUE TITLE
스테이지 클리어 효과음 재생 문제

### ISSUE THREAD

**Issue by StillnessFate** [inureyes/Galtron#359]
이전에 해결된 #303 이슈와 같습니다. createAlien 함수에서 스테이지 클리어 효과음을 재생할 경우 생성되는 적의 수 만큼 효과음이 중첨되면서 소리가 매우 커지고, 오디오채널을 전부 점유하기 때문에 일시적으로 다른 효과음이 재생되지 않습니다.
버그를 해결하거나 성능을 최적화하여도 이후에 Pull requests 에서 제대로 동기화하지 않은 코드들이 병합되어 같은 문제가 다시 발생하는 일이 많습니다...

**Comment by StillnessFate** [comment]
#360

**Comment by inureyes** [comment]
@StillnessFate 드디어 왜 iOS 버전업할 떄 마다 과거 버그가 다시 등장하는지 이해하셨군요.
