### ISSUE TITLE
파워샷 관련 버그

### ISSUE THREAD

**Issue by Keunmo** [inureyes/Galtron#366]
파워샷을 쓸 때 일반 총알이 안나갑니다.(혹시 의도된건가요?)
그리고 총알이 안나가는데도 스페이스바만 누르고 있어도 파워샷 게이지가 충전됩니다.

**Comment by Taewan-P** [comment]
네 파워샷을 쓸때 일반 총알이 나가지 않게 해달라는 이슈가 있었어요

**Comment by Taewan-P** [comment]
#230
