### ISSUE TITLE
적 기체 피격 효과음 추가

### ISSUE THREAD

**Issue by Alpacadabra** [inureyes/Galtron#371]
현재 적 기체가 피격당할 때의 효과음과 적 기체가 폭발할 때의 효과음이 같습니다.
듣기 안좋은건 아니지만 구분하는 편이 좋다고 생각합니다.

**Comment by moonkihun** [comment]
i will take it

**Comment by moonkihun** [comment]
확인해보니 둘의 사운드가 다르긴하지만 적 기체 폭발의 소리가 작아서 잘 안들린것 같습니다. 폭발의 소리를 올리는 것으로 수정완료했습니다.

**Comment by Alpacadabra** [comment]
@moonkihun 제가 잘못봤나 해서 코드를 전부 다시 훑어봤습니다만, 아무리 봐도 적 기체가 피격당할 때의 사운드와 폭발할 때의 사운드는 근본적으로 동일합니다. 그리고 애초에 적 기체의 피격 사운드 파일은 존재하지 않습니다.
어느 부분에서 둘의 사운드가 다르다는걸 확인하신 건가요?

**Comment by moonkihun** [comment]
아 제가 문제를 잘못 봤네요 다시해서 올리겠습니다.

**Comment by Alpacadabra** [comment]
[sounds.zip](https://github.com/inureyes/Galtron/files/1911712/sounds.zip)
이슈 해결과 관련하여 적당한 샘플 4개를 압축하여 올립니다. 라이선스도 포함되어 있습니다.
샘플을 그대로 사용하셔도 좋고, 다른 사운드를 원하시면 직접 찾아 사용하셔도 좋습니다.
이미 작동 확인도 끝난 파일들입니다. 볼륨과 이름만 변경하여 사용하시면 됩니다.
기존 라이선스를 수정하는 것도 잊지마세요.

오늘 오후 10시 안에 이 이슈가 해결되지 않을 경우 제가 직접 해결하겠습니다.
@moonkihun
