### ISSUE TITLE
몇몇 이미지를 불러 올 경우 경고 메세지를 출력 합니다.

### ISSUE THREAD

**Issue by 0-taku** [inureyes/Galtron#381]
![2018-04-12 4 35 04](https://user-images.githubusercontent.com/31723018/38639036-07675f9a-3e0b-11e8-9dd4-4c67b3f9f8a2.png)

위의 터미널과 같이 새로 추가된 하트 아이템과 같은 몇몇 이미지가 그려질때 오류가 생기는 것을 발견 할 수 있습니다.

**Comment by Alpacadabra** [comment]
이미 #372 에서 언급된 내용입니다.
