### ISSUE TITLE
아이템 획득 효과음 추가

### ISSUE THREAD

**Issue by Alpacadabra** [inureyes/Galtron#386]
아이템을 먹어도 아무런 효과음이 나지 않으니 조금 허전합니다.
아이템을 획득하면 효과음이 재생되게 하되 아이템마다 다른 효과음이 재생되었으면 좋겠습니다.

예) 방패 아이템을 획득하면 철이 부딪치는 소리가 재생되고 생명 아이템을 획득하면 띠리링 소리가 재생

**Comment by onnoo** [comment]
I take it
