### ISSUE TITLE
초시계 중첩버그

### ISSUE THREAD

**Issue by Aricsa** [inureyes/Galtron#393]
빠른 배속(w)을 여러번 누른 상태에서 초시계를 중첩해서 먹으면
더이상 초시계의 효과가 사라지지 않습니다

정확히는 초시계 하나를 먹고 다른 하나를 지속시간이 끝나기 전에 먹으면
초시계의 효과가 두번 사라지는게 아니라 한번만 사라집니다.

**Comment by onnoo** [comment]
I take it

**Comment by hoonski** [comment]
I solve it.
