### ISSUE TITLE
게임 속도를 조절하는 기능에 한계 설정하기

### ISSUE THREAD

**Issue by Ktw11** [inureyes/Galtron#398]
현재 게임속도를 조절하는 기능이 한계가 설정되어 있지 않아, 
극단적으로 빠르거나 느리게 게임 진행이 가능합니다.

이를 해결하기 위해 게임속도 조절하는 기능에 한계를 설정했으면 좋겠습니다.

**Comment by hoonski** [comment]
I take it

**Comment by hoonski** [comment]
I solve it.
