### ISSUE TITLE
retry시 bullet 버그

### ISSUE THREAD

**Issue by Ramenseller** [inureyes/Galtron#410]
Game을 RETRY하면 총알이 잘 안나가는 버그가 있습니다.
처음 게임을 시작하면 스페이스바를 꾹 누르면 총알이 연속적으로 나가는데
retry를 하면 총알이 연속적으로 나가지 않습니다.
이를 해결해주세요

**Comment by StillnessFate** [comment]
지금 테스트를 해보았는데 정상적으로 작동하는 걸로 보입니다. 아직도 문제가 발생하나요?

**Comment by Ramenseller** [comment]
잘 되네요
이슈 내리겠습니다.
