### ISSUE TITLE
적 둔화 아이템 이미지 변경

### ISSUE THREAD

**Issue by TideProphet** [inureyes/Galtron#420]
현재 적을 둔화시키는 아이템의 아이콘은 서비스 중인 온라인게임 '리그오브레전드'의 '초시계'라는 아이템의 아이콘을 그대로 가져다 쓴 이미지입니다. 
당연히 이는 저작권에 위배됩니다. 교체가 필요합니다.

* 적을 둔화시키는 아이템의 아이콘 변경

**Comment by moonkihun** [comment]
item_time.png이거 말하시는 건가요?

**Comment by hy-kiera** [comment]
제가 방금 확인해봤는데 바뀌어 있어요
