### ISSUE TITLE
Retry 시 차지샷이 남아있는 버그

### ISSUE THREAD

**Issue by TideProphet** [inureyes/Galtron#432]
게임오버 직전에 차지샷을 쏘고 재시도를 누를시 죽기전에 쏜 차지샷이 발사되던 상태 그대로 남아 재시도 시작과 동시에 다시 움직이기 시작합니다.

* 게임오버 후 재시도를 할 시 차지샷이 그대로 남아있는 버그 해결

**Comment by Ramenseller** [comment]
I'll take it
