### ISSUE TITLE
속도관련 아이템이 중첩되지 않도록 변경

### ISSUE THREAD

**Issue by TideProphet** [inureyes/Galtron#434]
현재 적을 느려지게 만드는 아이템이나 스피드아이템을 획득 시 그대로 중첩 연산값이 적용되는 현상이 발생합니다.
스피드 아이템의 경우 플레이어를 방해하는 수준이며, 둔화아이템의 경우 컴퓨터에 부하를 줍니다.
따라서 이 두 아이템이 적용되는 도중 추가로 아이템을 획득할 시 중첩연산이 되는 것이 아니라 지속시간만 초기화 되도록 변경해야 합니다.

* 스피드아이템과 적 둔화아이템을 여러개 먹을 시 중첩되는게 아니라 지속시간만 초기화되도록 변경

**Comment by Ochodus** [comment]
I'll take it
