### ISSUE TITLE
charge 게이지, ultimate 게이지 밑 라이프 글씨 추가

### ISSUE THREAD

**Issue by SonMinWoo** [inureyes/Galtron#442]
처음 게임을 접하는 사람들은 위 2개의 게이지가 무엇을 의미하는지 알기 힘듭니다.
따라서 게이지가 나타내는 것을 글로 적었습니다.
또한 기체의 색을 어둡게 했을경우 Life가 잘 보이지 않을 수도 있어 Life의 바로 밑에 LLife 글씨를 적었습니다.

**Comment by SonMinWoo** [comment]
제가 수정하였습니다.

**Comment by inureyes** [comment]
@SonMinWoo 이 부분의 커밋만 따로 떼서 풀리퀘스트를 넣어주세요. :)
