### ISSUE TITLE
마우스를 이용해서 게임을 시작할때 비정상적으로 종료됨

### ISSUE THREAD

**Issue by Taewan-P** [inureyes/Galtron#453]
마우스를 이용해서 게임을 시작할때 비정상적으로 종료됩니다.
buttonAction(stats, mouseBtnName, setting, screen, ship, aliens, bullets, eBullets)
TypeError: buttonAction() missing 1 required positional argument: 'charged_bullets'
라는 에러 메시지가 뜨고 비정상적으로 게임이 종료됩니다.

**Comment by hy-kiera** [comment]
charged_bullets라는 인자가 buttonAction()함수에 필요한데 위에는 그 인자가 없어서 TypeError가 뜬거 같아요. 간단하게 charged_bullets 인자를 추가해주면 되지 않을까요?

**Comment by Taewan-P** [comment]
@hy-kiera #452를 참고해 주세요 ㅎㅎ

**Comment by hy-kiera** [comment]
@Taewan-P #452 아직 머지가 안됐네요.
