### ISSUE TITLE
Release process (1.0)

### ISSUE THREAD

**Issue by inureyes** [inureyes/Galtron#463]
* This issue discusses release process (1.0)

**Comment by inureyes** [comment]
I added maintainers to Assignnee list. Please check the [notice post](https://erica.codeonweb.com/entry/0b63392c-d2fa-4144-9ceb-d18763589a95).

**Comment by Taewan-P** [comment]
닫힌 이슈들의 Milestone을 모두 1.0으로 변경하였습니다.

**Comment by Alpacadabra** [comment]
몇 가지 질문을 드립니다.
1. Pull request 하나에 여러 issue들이 해당되어 있는 경우 어떻게 배점을 해야하나요?
2. Pull request 에 해당하는 issue가 없을 경우 어떻게 배점을 해야하나요?
3. Pull request 에 점수가 누락되어 있을 경우 어떻게 배점을 해야하나요?
4. 한 Issue 를 여러 학생이 해결했을 경우 Assignee에 여러 명을 설정해도 되나요?
5. Assignee 를 설정할 수 없는 경우 (목록에 나오지 않음) 어떻게 해결해야 하나요?
