### ISSUE TITLE
점수가 소숫점으로 나타나는 현상

### ISSUE THREAD

**Issue by Taewan-P** [inureyes/Galtron#464]
![image](https://user-images.githubusercontent.com/27392567/39186387-3992cdac-4805-11e8-9555-c718005d0d25.png)

적은 점수를 획득하였을때 위 사진과 같이 소숫점으로 점수가 표기됩니다. 이를 수정할 필요가 있어 보입니다.
+ 소숫점으로 뜨는건 w키 옵션으로 속도를 증가시켰을 시에 일어나는 현상입니다.

**Comment by PrismSpirit** [comment]
I'll take it.
