### ISSUE TITLE
게임 강제 종료 현상 해결

### ISSUE THREAD

**Issue by TideProphet** [inureyes/Galtron#74]
Galtron에 등장하는 외계인들은 점점아래로 내려옵니다.
이 외계인을 잡지 않고 총알만 회피하면서 외계인이 화면하단까지 닿기를 기다릴 경우 외계인이 하단에 닿는 순간 게임이 강제 종료됩니다.
 게임오버로 처리하거나 외계인이 다시 위로 올라가도록 하여 이를 해결해야 합니다. 
 | |
 | |
| |
| |
#Edited 
종료현상은 플레이어 기체의 모델과 외계인 기체가 일정이상 가까워 졌을때 모델링이 겹치면서 일어나는 현상으로 밝혀졌습니다. 수정해야할 사항이 이에따라 변경되었습니다. 그리고 외계인을 모두 잡아야 스테이지가 클리어 되는데 외계인이 화면 밑까지 내려갈 경우 이를 잡지 못해 영원히 클리어가 불가능해 집니다

* 외계인과 플레이어의 기체가 접촉할시 목숨을 하나 잃도록 수정
* 외계인이 화면아래로 내려갈 경우 다시올라가거나 게임오버되도록 수정

**Comment by dudu0166** [comment]
i will take it

**Comment by TideProphet** [comment]
ISSUE의 내용에 이상이 있음을 발견했고, 수정하였습니다.

**Comment by hy-kiera** [comment]
I'll take it

**Comment by StillnessFate** [comment]
@hy-kiera This issue has not been fixed. I will solve this problem.

**Comment by hy-kiera** [comment]
잘못 assign된 줄 알고 지웠네요. 다시 assign 했습니다.
