### ISSUE TITLE
목숨 소멸시 적의 기체 초기화 해결

### ISSUE THREAD

**Issue by ujma1234** [inureyes/Galtron#80]
목숨 소멸시 적의 기체가 초기화되는 상황을 해결

(한마리 남기고 죽으면 한마리 남긴체로 시작)

**Comment by TideProphet** [comment]
목숨을 잃을 시 화면자체가 초기화되는 (외계인을 1마리만 남겨도 새로운 화면에서 다시 16마리로 시작하는) 현상을 해결해야 한다는 뜻인가요? 혼동의 여지가 있으니 Issue내용을 바꾸는게 좋을 거 같습니다.

**Comment by StillnessFate** [comment]
This issue has been resolved.
