### ISSUE TITLE
필살기

### ISSUE THREAD

**Issue by hy-kiera** [inureyes/Galtron#83]
적을 명중시키면 게이지가 찬다(예를 들어 +5씩 총 100)
게이지가 100%를 다 채우면 필살기 기술을 사용할 수 있게 된다.
필살기 키는 'f'로 하고 6~7의 적을 처리할 수 있다.

+ 필살기 사용할 때 이팩트 다르게 처리

**Comment by hd132506** [comment]
I'll take it

**Comment by hy-kiera** [comment]
필살기 만들 때 전체 적을 다 처리하는 것도 괜찮을거 같아요.

**Comment by RDCPP** [comment]
What do you think about using 'q' key instead of 'f' key?
