### ISSUE TITLE
Add GameOver Scene

### ISSUE THREAD

**Issue by onnoo** [inureyes/Galtron#87]
When I play the Galtron, I meet a game ending with the background of last game.
So I want to add a new dynamic gameover scene after game ending.

component of GameOver scene is
* My score
* Retry button
* Return to Menu button
* Quit button

**Comment by 0-taku** [comment]
i will take it

**Comment by hyobins** [comment]
I'll take it

**Comment by hyobins** [comment]
#255 
Add GameOver Scene(#87) is solved
