### ISSUE TITLE
Add a Main BGM(Background Music) 

### ISSUE THREAD

**Issue by Verssae** [inureyes/Galtron#89]
Add a BGM will be playing in main scene background.
The music must be played back repeatedly.
The music must be in compliance with the license.

**Comment by jil8885** [comment]
음악은 PPAP쯤으로 합시다

**Comment by habby9000** [comment]
i will take ittttt

**Comment by habby9000** [comment]
fixes #89

**Comment by taaeyoon** [comment]
i'll take it

**Comment by TigerP-MS** [comment]
I will take it

**Comment by Verssae** [comment]
resolved by @habby9000 at #147

**Comment by Verssae** [comment]
resolved by @habby9000 at #147
