### ISSUE TITLE
기체 색 변경 기능 추가

### ISSUE THREAD

**Issue by Alpacadabra** [inureyes/Galtron#95]
시작하기 전에 여러 색이 적용된 기체들을 보여주고 그 기체들 중에서 선택할 수 있도록 하는 식으로
처음 선택창에서 기체 색을 변경할 수 있게 한다.

**Comment by BeautifulTommorow** [comment]
i will take it

**Comment by YoonkiKim1** [comment]
I will take it

**Comment by moonkihun** [comment]
i will take it

**Comment by StillnessFate** [comment]
#155 This issue has been resolved.
