### ISSUE TITLE
색반전 기능 추가

### ISSUE THREAD

**Issue by BeautifulTommorow** [inureyes/Galtron#96]
메뉴화면에 옵션 탭을 만든 후, 색반전 기능을 추가

**Comment by Ramenseller** [comment]
I'll take it

**Comment by taaeyoon** [comment]
I will take it

**Comment by Taewan-P** [comment]
taaeyoon님 collaborator 로 등록이 안되있어서 Assignee 지정이 안되네요.
일딴 해결되었으므로 닫겠습니다.
