### ISSUE TITLE
Mouse UI

### ISSUE THREAD

**Issue by StillnessFate** [inureyes/Galtron#97]
You need to modify the menus so that you can use the mouse as well as the arrow keys.

**Comment by ksccmp** [comment]
i'll take it

**Comment by hyobins** [comment]
I'll take it

**Comment by ksccmp** [comment]
i'll take it

**Comment by StillnessFate** [comment]
@ksccmp This is not what I want. You misunderstand the content of the issue. You should be able to manipulate the menu with your mouse, not by manipulating ship with your mouse. #221

**Comment by StillnessFate** [comment]
#294
