### ISSUE TITLE
적을 일정이상 처치시, 보스 생성

### ISSUE THREAD

**Issue by Ktw11** [inureyes/Galtron#98]
적을 25마리 이상 처치시, 일반 적보다 크기와 체력이 큰 보스를 등장시키기.
보스는 플레이어의 공격을 20회 맞아야 처치가 되며 보스의 크기는 일반 적 크기의 3배이며 2배의 속도로 이동한다.

**Comment by hy-kiera** [comment]
#78 과 똑같지 않나...? 중간보스?

**Comment by hoonski** [comment]
I will take it.

**Comment by kyj0701** [comment]
I will take it.
