### ISSUE TITLE
시간이 흐를수록 적 방어력 상승

### ISSUE THREAD

**Issue by hoonski** [inureyes/Galtron#99]
1분이 지날 때 마다 적을 처치하기 위해 공격을 맞추어야하는 횟수가 1씩 증가한다.

**Comment by hoonski** [comment]
Label을 붙일 수 있는 권한이 따로 있는 것인지 궁금합니다.

**Comment by anmyeondo** [comment]
i will take it

**Comment by inureyes** [comment]
@hoonski collaborator에게만 권한이 주어집니다. 지금은 조 당 한 명씩에게만 부여했습니다.

**Comment by onnoo** [comment]
I got it!
